### PR TITLE
Adds AM/PM Arrows to toggle between states

### LINKED ISSUE #121: Would it be possible to add an arrow for the AM/PM component as well?
That would be great for UX :)

### PR DESCRIPTION
**Pull request by davidfurlong**
fixes #121

### CODE REVIEW

**Comment by simeg** [comment]
Please run the linter and fix the errors. Then I'll merge this. Thanks.

**Comment by davidfurlong** [comment]
@simeg my bad, fixed now

**Comment by simeg** [comment]
Thanks @davidfurlong. Please for future PRs see [this.](http://chris.beams.io/posts/git-commit/#imperative)

**Comment by davidfurlong** [comment]
@simeg thanks for the suggestion

**Pull request merged**
