### PR TITLE
added isDisabled prop to datetime field

### PR DESCRIPTION
**Pull request by export-mike**
allowing the text fields to be disabled

### CODE REVIEW

**Comment by tmartensen** [comment]
Bumping, could this get merged?

**Comment by export-mike** [comment]
Umm this was so long ago I'll have to take a look next week and cast my mind back to its use case

**Comment by light049** [comment]
Will this prop be covered with inputProps={{disabled: true}} ?

**Comment by simeg** [comment]
Hi @export-mike and thanks for the PR, 

As @light049 mentions you can use the `inputProps` prop to disable the input field, just like this:

`<Datetime inputProps={{ disabled: true }} />`

**Pull request closed without merging**
