### PR TITLE
fix #162 onFocus() and onBlur triggered on inconsistent state.

### LINKED ISSUE #162: onFocus() and onBlur triggered on inconsistent state.
`onFocus()`and `onBlur()` are triggered when state is set not when state is applied. This lead to inconsistent behaviour. 

For example.
1. click on input
2. datetime `setState( open:true )`
3. datetime call`onFocus()`
4. parent component re render to change style or whatever
5. datetime `componentWillReceiveProps()` is executed and state is recalculated based on inconsistent state ( open=false)
6. datetime will never open

### PR DESCRIPTION
**Pull request by gvelo**
fix #162 onFocus() and onBlur triggered on inconsistent state.

### CODE REVIEW

**Comment by simeg** [comment]
Hi @gvelo. Thanks for your contribution, before I look at this PR it must however pass the tests. Please fix your changes to make Travis happy and I'll take a look at this PR.

**Comment by kbouchard** [comment]
Can't wait to get this fix merged, It's messing up with my forms behaviors right now. @simeg any ideas when you'll be able to merge that ?

Tx @gvelo for the fix !

**Comment by simeg** [comment]
@kbouchard I'll try to find some time as soon as possible! Thanks for your patience.

@gvelo for future PR's, please use the PR template. Thanks!

**Comment by damianprzygodzki** [comment]
Please, let's merge that! Is there any way i can help with that? OnBlur is now not working at all. And i am forced to change datepicker.

**Comment by simeg** [comment]
@damianprzygodzki you're the third person asking for this (including the other people in this PR).

I'll take a look at this tonight.

**Comment by cadavre** [comment]
+1 for this!

**Comment by simeg** [comment]
This fix indeed looks good. Thanks for the help @gvelo! But please use the PR template for any future PRs :) It makes it much easier for me.

@kbouchard @damianprzygodzki @cadavre I'll release a new version later tonight. Thanks for your patience.

**Pull request merged**
