### PR TITLE
Create proper demo application

### PR DESCRIPTION
**Pull request by MrLeebo**
### Description

I was experimenting with various react-datetime configurations and I thought I would turn that energy into a proper demo application because you mentioned your desire to have one in the [backlog](https://github.com/YouCanBookMe/react-datetime/projects/2).

The demo app is just a basic `create-react-app` app with some customizable examples
showing off how react-datetime can be used.

Deploy the demo to github with `npm run deploy` (you will need to rerun this command to apply changes in the future)

Access the demo (after deploying) from https://YouCanBookMe.github.io/react-datetime

I have [deployed the demo to my fork](https://mrleebo.github.io/react-datetime/) so you can see how it will look before you merge this.

### Motivation and Context
Your project page noted that this was something you wanted to do, and I happened to be exploring the component to better understand its behavior.

### Checklist

```
[ ] I have added tests covering my changes
[ ] All new and existing tests pass
[x] My changes required the documentation to be updated
  [ ] I have updated the documentation accordingly
  [ ] I have updated the TypeScript 1.8 type definitions accordingly
  [ ] I have updated the TypeScript 2.0+ type definitions accordingly
```

### CODE REVIEW

**Comment by simeg** [comment]
Hi @MrLeebo. Thanks for this contribution. I looked at your forked demo and it looks really nice. Someone will have to look through this more carefully before merging and maybe think about the impact etc. Really nice job on this!

**Comment by MrLeebo** [comment]
@simeg anything I can do to help this get merged?

**Comment by layneanderson** [comment]
This is well thought out and well written.  I can't think of any downsides to this.

**Comment by simeg** [comment]
@layneanderson I did the code review as well and it looks good to me.

We should think about how to deploy this continuously with the normal deployment, since this requires `npm run deploy` to be run.

@MrLeebo Sorry for the delay, and thanks a lot for this - it looks great. I'll move the backlog ticket to done!

**Comment by layneanderson** [comment]
I created a `gh-pages` branch and deployed the demo.  The branch contains only the build.  This is by no means automated (yet), but I thought it would be good to make it live.

**Pull request merged**
