### PR TITLE
added option to add child components to DateTime

### PR DESCRIPTION
**Pull request by besuikerd**
as per request in #45 and #74, added an option to 'decorate' the input component. 

usage:

``` javascript
<DateTime 
  inputDecorator={
    (input) => <div>
      <div className="someDecoration">
        {input}
      </div>
    </div>
  }
/>
```

### CODE REVIEW

**Comment by simeg** [comment]
@besuikerd Bump for looking over the failing test.

@chollier @arqex Bump, please consider merging this soon.

**Comment by chollier** [comment]
I'm not part of this fork, please stop mentioning me. I stopped maintaining the repo this project is based from, it's not to get mentioned on pull requests on the (best) fork. 





On Mon, Jul 4, 2016 at 1:10 AM -0700, "Simon Egersand" <notifications@github.com> wrote:












@besuikerd Bump for looking over the failing test.



@chollier @arqex Bump, please consider merging this soon.

**Comment by simeg** [comment]
I'm sorry. I'm just eager to get some stuff merged so I can use it in my work and I saw you were the top contributor. Wont happen again (beside this apology which you might get notified for - sorry!).

**Comment by davidfurlong** [comment]
Your CI checks are failing for reasons not related to this PR. @simeg you would have to wait for a release regardless, I'd recommend installing and using your fork for the time being. Syntax is `npm install simeg/yourforkname`

**Comment by simeg** [comment]
I'm closing this. Continue discussing in #153.

**Pull request closed without merging**
