### PR TITLE
Fix for AM/PM toggle (fixes #446)

### LINKED ISSUE #446: Using the input to change AM/PM does not update the time input view
### I'm Submitting a ...
```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
1. Open the time view
2. Change the AM/PM portion of the timestamp in the textbox

### Expected Results
The the toggle for AM/PM should update appropriately

### Actual Results
The toggle does not update

### PR DESCRIPTION
**Pull request by mattbasta**
### Description
Fixes issue #446 

### Motivation and Context
Please see issue #446 for details

### Checklist
```
[ ] I have added tests covering my changes
[x] All new and existing tests pass
[ ] My changes required the documentation to be updated
  [ ] I have updated the documentation accordingly
  [ ] I have updated the TypeScript 1.8 type definitions accordingly
  [ ] I have updated the TypeScript 2.0+ type definitions accordingly
```

### CODE REVIEW

**Comment by mattbasta** [comment]
Note that there are existing snapshot test failures on master for me locally, but the number of failures does not change after my patch.

**Comment by layneanderson** [comment]
Please see my comments on issue #446

**Comment by simeg** [comment]
I can confirm that this fix works for the case where you change the AM/PM value in the textbox and it also updates the input field value.

👍

**Comment by layneanderson** [comment]
Thanks Simon, will try get this merged soon.

**Comment by simeg** [comment]
Since the build is now OK again I'm merging this.

**Pull request merged**
