### PR TITLE
added touch support

### PR DESCRIPTION
**Pull request by davidworkman9**
To partial address #487 that I opened this morning, I've added touch support for tapping and holding. (this does not address the double tap to zoom issue on the iOS 10. I can't seem to find a way to turn that off).

### CODE REVIEW

**Comment by simeg** [comment]
Hi @davidworkman9. The code looks good, but I'm wondering how much value this adds since it doesn't seem to be compatible with much.

* https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ontouchstart#Browser_compatibility
* https://developer.mozilla.org/en-US/docs/Web/Events/touchend

Have you verified using iOS?

**Comment by davidworkman9** [comment]
Yes, it was working on the iPad when I wrote it, iOS 11 I believe. Weird that MDN doesn't have information on the touch start event. The touchend event is supported on android & iOS safari in that link you sent, you need to click the mobile tab. According to (caniuse)[https://caniuse.com/#feat=touch] there's full support for touch events on iOS since 3.2 and android 2.1

**Comment by simeg** [comment]
Great, let's get this merged then.

You still need to make Travis happy, just run `npm run test:snapshot:update` and push the changes in a separate commit.

**Comment by simeg** [comment]
@davidworkman9 Any chance you could do another commit with the fix? :)

**Comment by davidworkman9** [comment]
Unfortunately I'm no longer with the company that this PR was made under. @chrislink14 should be able to though!

**Comment by chrislink14** [comment]
After running the snapshot update test, those test pass fine but I am getting this failed test now.
` PASS  test/snapshots.spec.js
 FAIL  test/tests.spec.js
  ● Datetime › persistent valid months going monthView->yearView->monthView

    expect(received).toEqual(expected)
    
    Expected value to equal:
      true
    Received:
      false
      
      at Object.<anonymous> (test/tests.spec.js:81:107)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:126:13)
      at process.emit (events.js:214:7)
      at emit (internal/child_process.js:772:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by simeg** [comment]
@chrislink14 Have you rebased on top of master? I think that will fix the failing test.

**Comment by simeg** [comment]
Hmm. Seems like the snapshots are written for a specific timezone (mine). That's not good.

You know what? I'll "hijack" this PR and make Travis happy, you shouldn't have to do all this stuff to make the CI green. Thanks a lot for this, both of you!

**Comment by simeg** [comment]
See #506. Will close this PR now. Again, thank you both for this.

**Pull request closed without merging**
