### PR TITLE
Keyboard support and date config options

### PR DESCRIPTION
**Pull request by techanvil**
## Description

Have added keyboard functionality to reproduce the shortcuts for https://angular-ui.github.io/bootstrap/#/datepicker.

Also added the following config options:

`renderDayHeader`
`startingDay`
`monthColumns`
`yearColumns`
`yearRows`
`allowTabs`
## Motivation and Context

I needed to replicate Angular UI Bootstrap Datepicker in React, and these changes allow that to happen while retaining compatibility with the current React Datetime.

## Checklist

- [x] My change required changes to the documentation.
- \- [x] I have updated the documentation accordingly.
- \- [ ] I have updated the TypeScript type definition accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Please note I have added quite a few tests for the keyboard controls, but tests need to be written for the other new options.

The TypeScript definition also needs updating.

I am happy to make these changes if you are interested in merging this PR. I can also revert any unneeded changes to the README.

### CODE REVIEW

**Comment by simeg** [comment]
Hey @techanvil, thanks for your contribution.

There's a lot of things happening in this PR - it will take some time for me to look through everything. For future PR's, please divide your changes into multiple PR's. It will make the process go by a bit faster :)

**Comment by techanvil** [comment]
Hey Simon

Thanks for taking a look. Sorry there is so much going on! These changes
are driven from a requirement at work so I've had to make these changes
quite quickly. I'll certainly aim for smaller PRs in future.

Would be nice to merge this functionality into your codebase, let me know
if there's anything which is not mergeable and we can remove or amend it.

Cheers

Tom

**Comment by techanvil** [comment]
BTW I have enabled "allow edits from maintainers" in case you want to make any changes directly yourself.

**Comment by simeg** [comment]
Hey again @techanvil. Ah, if it's requirements from work it makes sense that all of these changes came at once. I have been thinking about this PR for a while and honestly, there's too much going on for me to merge it with a good conscious. A lot of people are using this component (at the moment there's 41k downloads / month), so there's potentially _a lot_ of people using it. That's why I want to 100% certain of what I allow to be in the codebase. 

I see that there's many changes to the current codebase which is why I feel like this PR is too big to be merged all at once. If you feel like you _really_ want these things to get merged I will have to ask you to create smaller PRs, one feature per PR sounds reasonable. That way I can think it through and also write my own tests (if necessary).

I hope you understand, I appreciate your contribution but I have to think about the wellbeing of the component. I'm interested in hearing your thoughts so I won't close this right now. Thank you.

**Comment by techanvil** [comment]
Hey Simon

Thanks for getting back to me. I understand and agree, it's too much to
merge in as it stands.

I think it might be nice to merge some of the stuff I've done - for
example, the keyboard controls are a self contained feature that could be
introduced via a new option to be non disruptive to existing users. Seeing
as I've done the work, it seems like it would be good to supplement the
functionality as long as it's backward compatible, performant etc. - if you
agree, of course.

I'll just have to see if I can find the time to factor anything out into
bite size chunks.

Assuming you like the idea, I'll endeavor to do this, and keep you posted
if/when I make some progress.

Cheers

Tom

**Comment by simeg** [comment]
Hi @techanvil. Sorry for the late response.

I quite like the keyboard functionality (assuming it works the same way as in the example you provided). If you could extract that functionality and submit it as a PR following the guidelines I'd be happy to review it! It could potentially be something we could add in the upcoming v3 release. 

Let me know what you think.

**Comment by simeg** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
