### PR TITLE
Customizing the time picker

### PR DESCRIPTION
**Pull request by bandanaman**
I extended time view widget to switch between am/pm and 24h clock modes basing on time format, as arqex described in his post https://github.com/YouCanBookMe/react-datetime/issues/41#issuecomment-190843119

### CODE REVIEW

**Comment by serkandurusoy** [comment]
Wow this is exactly what I also needed! Thanks. @YouCanBookMe do you think you can get this merged and published?

**Comment by kaiyes** [comment]
@arqex this would help me as well. it would be really great if this is merged !

**Comment by ecerroni** [comment]
I'd like to see this PR accepted and merged. I also need that feature ASAP.

**Comment by janoschpizza** [comment]
+1 on this

**Comment by robfallows** [comment]
+1 here too. Would be really useful!

**Comment by arqex** [comment]
Hey @bandanaman 

Thanks for the PR, I think it will need more work to also accept the `a` parameter in the timeFormat, 

maybe checking `timeFormat.match(/a$/i)` do the trick. Since a lot of people needs this feature I decided to merge it now.

**Comment by serkandurusoy** [comment]
Thank you all, this feature will be very valuable for me!

**Comment by kaiyes** [comment]
Thanks a lot !

**Comment by kahurangitama** [comment]
I have an app where in some places I need to use regular date picker (without time picker) and want to use the same plugin but without this feature. Is there some option to turn off the ability of time picking?

**Pull request merged**
