### PR TITLE
Add label prop to have a label text in input

### PR DESCRIPTION
**Pull request by light049**
I just added a label prop for user who want the input to have a label text at left side.
And update required layout followed bs styles.

### CODE REVIEW

**Comment by simeg** [comment]
Hi @light049, thanks for the PR.

I'm not sure how I feel about letting this component have the responsibility for the label. The label *does* belong to the form and the SEO would increase (if the `<label>` element was used). 

What do you think @arqex?

**Comment by light049** [comment]
If that's naming issue, might just use other prop name like inputLabel?

**Comment by simeg** [comment]
The naming is not the problem, the problem is defining what the component should be responsible for. Let's wait and see what @arqex thinks, as he is the author for the component :) If he thinks it's a good idea I think we can re-write the code a bit before we merge it, but we can discuss that later.

**Comment by simeg** [comment]
Thinking about this, the **only** reason I see to merge something like this is that the SEO score would increase if you wanted to use a label. Otherwise I think it's nice to keep this component clean of any additional stuff. You can always add some text that will act as a label outside of the component. 

This is of course just my idea of what the component should and should not do. Any good reasons why you think this should be included in the component @light049?

**Comment by arqex** [comment]
From my point of view, we should create a way of completely edit the markup of the component. There is a lot of people who are requesting this kind of changes like:

https://github.com/YouCanBookMe/react-datetime/pull/82
https://github.com/YouCanBookMe/react-datetime/pull/152

Somebody need a reset button, other a label, other an icon in the input...

I don't think react-datetime needs to include any code to please those specific users, but a way of letting them customize the component as they need. Currently, we have the `renderMonth`(day, year) props. Maybe we need to add the `renderInput` and `renderView` ones.

**Comment by simeg** [comment]
@arqex Good! Then we share the same opinion, because I was literally just writing issue #153, which would resolve this and many other issues.

**Comment by simeg** [comment]
I'm closing this. Continue discussing in #153.

**Pull request closed without merging**
