### PR TITLE
Add callback on view mode changes

### PR DESCRIPTION
**Pull request by josefernand**
### Description

Add a callback trigger on view mode change that receives a single string param with the new view mode value.
### Motivation and Context

It will be useful to know when the view mode change and what is the new view mode.
### Checklist

```
[x] I have added tests covering my changes
[x] All new and existing tests pass
[x] My changes required the documentation to be updated
  [x] I have updated the documentation accordingly
  [x] I have updated the TypeScript 1.8 type definitions accordingly
  [x] I have updated the TypeScript 2.0+ type definitions accordingly
```

### CODE REVIEW

**Comment by simeg** [comment]
Hi @josefernand, sorry for the late response. I think this is a good idea and that the implementation code + tests look good. Great work!

But the tests are already fixed in a PR that was merged today, so you can remove that commit (f1c21483ee24a954e1aff844f4ea5f24f3843f12). Also the code for TS typings will have to be changed too since one of those files don't exist any more. Plus you don't have to build the component on your own, so remove that commit too please (337459a1f39ea032a6e146447723d1a44416bfca).

Sorry for the conflicts, but I don't think they should be hard to resolve.

**Comment by josefernand** [comment]
Hi @simeg thanks for your help. I have already reverted those commits. Please let me know if you need me to do something else on my side. Happy to contribute. Thanks.

**Comment by simeg** [comment]
Hi @josefernand. So when I said remove I meant rebase and force push. Sorry for not being clear about that. Also again sorry for the late delay. As you can see this PR cannot be merged because it needs rebasing.

So what I would like for you to do is:
1) Drop commits f1c2148, 0d4324c, 337459a and 4d17fe7 (`git rebase --interactive` is your friend)
2) Rebase, resolve any conflicts and then force push

It's normal workflow for creating PRs like this. 

Thanks alot!

**Comment by simeg** [comment]
@josefernand 

I took your changes and put into my own PR (#389). I'm sorry for not merging this, and I know it's my fault for being so slow at responding but the code looked too good to just be laying around here. So now it's merged in master. Thanks so much for your contribution! Will release a new version with this included in it soon.

**Comment by josefernand** [comment]
Hi @simeg sorry I've been offline for some days. Don't worry and thanks for take in mind this feature.

**Pull request closed without merging**
