### PR TITLE
Update dependencies for React 15.5

### PR DESCRIPTION
**Pull request by andjosh**
Lots of deprecation warnings coming in [React 15.5.0][0].

### Description
I just updated this package to use `create-react-class` and `prop-types` (read about them in the linked blog post above, or in the commit comments).

### Motivation and Context

This removes a bunch of pesky warnings.

### Checklist
```
[x] All new and existing tests pass
```

Addresses: #305 

[0]: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

### CODE REVIEW

**Comment by pteigen** [comment]
Please accept this pull request. Thanks

**Comment by simeg** [comment]
Hey @andjosh and everyone. Sorry for the delay. This PR is clean and explicit - I like it. However updating the dist files is not something you have to do, we do that when we release a new version. I'll release a new version soon after merging this PR.

**Comment by ccorcos** [comment]
@simeg how soon? ;)

**Comment by simeg** [comment]
@ccorcos 2.8.10 is now published!

**Comment by mattgi** [comment]
awesome, thanks mate.

**Pull request merged**
