### PR TITLE
Add instructions for openCalendar

### PR DESCRIPTION
**Pull request by SachaG**
Document how to use openCalendar.

### CODE REVIEW

**Comment by simeg** [comment]
I'm not sure I want to "encourage" using `ref` with the component. If you are using `ref` with a React component it's usually something wrong, so let's try to fix what's wrong instead of encouraging bad practice.

What do you say? @SachaG

**Comment by SachaG** [comment]
I don't disagree, but then what would the ideal API look like?

**Comment by SachaG** [comment]
I guess we could just rely on `open` instead. My main reason for wanting to use `openCalendar` was to differentiate between "I want to trigger this calendar's opening" and "I want this calendar to remain in an open state", which I thought was more what `open` was for. But maybe that's not really a meaningful distinction.

**Comment by simeg** [comment]
I think it is a meaningful distinction, but can't this be done today _with_ the `open` prop? If you consider it to be a state it makes sense to use it for both, then you could just write your own `openCalendar`:

```js
const openCalendar = bool => bool;
<Datetime
  open={openCalendar}
/>
```

**Comment by SachaG** [comment]
True. Is #510 worth fixing then? Or should people just not use `openCalendar`?

**Comment by simeg** [comment]
If your issue is solved, then feel free to close it. I'd not advise people to use that function using refs.

**Comment by SachaG** [comment]
OK.

**Pull request closed without merging**
