### PR TITLE
Move @types/react back to devDependencies

### PR DESCRIPTION
**Pull request by cwmacdon**
### Description
See https://github.com/YouCanBookMe/react-datetime/issues/408 for details

### CODE REVIEW

**Comment by simeg** [comment]
Hi @cwmacdon and thanks for your contribution! As I'm not a TypeScript user I'm having a hard time seeing the impact of this change. With this change we're basically saying that the package `@types/react` is not a requirement to use this component, just during development. I'm not sure what `@types/react` brings to the table in the first place. If you know, would you mind explaining it to me? Thanks.

**Comment by cwmacdon** [comment]
Hey @simeg,

Yes, all TypeScript definition files (any module in the @types namespace) should be development dependencies only. See [this TypeScript issue](https://github.com/Microsoft/TypeScript/issues/9731#issuecomment-232864820)

---- Some details below on what is actually going on ----

The issue here is that npm is resolving the packages and gives a special priority to packages defined as `dependencies` vs `devDependencies`.

Here is a detailed look at how things are being resolved and what is going wrong:

If you look at the example `package.json` file from the [issue](https://github.com/YouCanBookMe/react-datetime/issues/408), you can see how a typical typescript project should be set up. If my project is being developed against react v15 and I include your `react-datetime` as a dependency, then npm will resolve as follows:

1) looks at `react-datetime` dependencies, and installs `@types/react@16.0.5` in top level `node_modules` (or latest >=15)
2) looks at local devDependencies, and sees `@types/react@15.6.1`. It will move `@types/react@16.0.5` to `node_modules/react-datetime/node_modules/@types/react`, and then install `15.6.1` in my top level `node_modules`

Now the `node_modules` looks like this:

- react
- react-datetime
  - Datetime.d.ts
  - node_modules
    - @types
      - react
- @types
  - react@15.6.1

Now when the TypeScript compiler is looking at the following code:
```
import * as React from 'react';
import * as Datetime from 'react-datetime';
```

It grabs `@types/react@15.6.1` from the first line.
Then from the second line it grabs: `react-datetime/Datetime.d.ts`.
This file imports from `react`, and the compiler first attempts to resolve locally, so it looks inside `react-datetime/node_modules/@types` and pulls in `@types/react@16.0.5`
Now the compiler has multiple competing definitions, and can't know which one is right, so it throws errors.

**Comment by cwmacdon** [comment]
If you run `npm dedupe`, it figures out that the `@types/react@15.6.1` solves the constraint defined by `react-datetime` looking for `@types/react >= 15`, so it removes the extra package, and everything works fine. Unfortunately this isn't a reasonable workaround, since dedupe takes forever, and can't be targeted at a single package.

**Comment by simeg** [comment]
Thanks for that thorough explanation. This seems to be a reasonable change. Thanks a lot for your contribution.

**Pull request merged**
